### ISSUE TITLE
Science Snippet Video Link

### ISSUE THREAD

**Issue by mnschrandt** [tbep-tech/robinson-sport-fish#6]
The Science Snippet/Short for the Robinson Preserve Acoustics download, conducted December 2022, has just been posted to FWRI's YouTube Channel:
https://youtube.com/shorts/2IWgYjh7rh8?feature=share

Let's add this link to the project updates page.

**Comment by jonpeake** [comment]
Added to both the updates page and the main page with https://github.com/tbep-tech/robinson-sport-fish/commit/9025ecc9e5d03d8dc9b90a18a763f0da183bed75
